# Copyright (c) DarkEmu
# Compose setup for ConnectServer and GameServer.

services:
  connectserver:
    build: .
    command: ["/app/build/server/Connect/DarkheimCS"]
    ports:
      - "44405:44405"
    volumes:
      - ./server/Connect/Data/ServerList.json:/app/server/Connect/Data/ServerList.json:ro
    working_dir: /app
    restart: unless-stopped

  gameserver:
    build: .
    command: ["/app/build/server/Game/DarkheimGS"]
    ports:
      - "55901:55901"
    working_dir: /app
    restart: unless-stopped
